##################################################################
# File               : .github/workflows/docker-image.yml
# Description        : GitHub Action for creating a Docker image
# Maintainer(s)      : richardgarryparker@gmail.com
# Created            : 2025-03-16
# Last updated       : 2025-03-16
# Change Log :
#   2025-03-16       : First release
##################################################################
name: Publish to GHCR

on:
  push:
    branches:
      - '*'
    tags: ['*']

# Prevent concurrent execution of this action
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# The Docker image is created with name `$repo_owner/$repo-name`.
# For example, `pichardrarker/header-hook`. To change
# this, modify the value for `IMAGE_NAME`
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04

    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Metadata extraction differs according to
      # GitHub branch. If "main", then the "latest"
      # tag is given to the image. If anything but
      # main, then only the branch name and SHA
      # are provided as tags
      - name: Extract metadata (tags, labels) for Docker (main branch)
        id: metamain
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=tag
        if: github.ref == 'refs/heads/main'

      - name: Extract metadata (tags, labels) for Docker (non-main branch)
        id: metanonmain
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            type=ref,event=tag
        if: github.ref != 'refs/heads/main'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Slightly different build steps, depending on
      # GitHub branch
      - name: Build and push Docker image (main branch)
        id: pushmain
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/Dockerfile # Use custom Dockerfile (remove this line if using default 'Dockerfile')
          push: true
          tags: ${{ steps.metamain.outputs.tags }}
          labels: ${{ steps.metamain.outputs.labels }}
        if: github.ref == 'refs/heads/main'

      - name: Build and push Docker image (non-main branch)
        id: pushnonmain
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/Dockerfile # Use custom Dockerfile (remove this line if using default 'Dockerfile')
          push: true
          tags: ${{ steps.metanonmain.outputs.tags }}
          labels: ${{ steps.metanonmain.outputs.labels }}
        if: github.ref != 'refs/heads/main'
